import { pgTable, bigint, text, boolean, integer, timestamp, serial } from 'drizzle-orm/pg-core'

// esim-manager 프로젝트의 TypeORM 엔티티 기반 Drizzle 스키마 (읽기 전용)

export const orders = pgTable('order', {
  productOrderId: bigint('productOrderId', { mode: 'number' }).primaryKey(),
  orderId: bigint('orderId', { mode: 'number' }),
  productOrderStatus: text('productOrderStatus'),
  lastChangedType: text('lastChangedType'),
  paymentDate: timestamp('paymentDate'),
  lastChangedDate: timestamp('lastChangedDate'),
  claimType: text('claimType'),
  claimStatus: text('claimStatus'),
  receiverAddressChanged: boolean('receiverAddressChanged'),
  productName: text('productName'),
  productOption: text('productOption'),
  placeOrderDate: timestamp('placeOrderDate'),
  quantity: integer('quantity'),
  totalPaymentAmount: integer('totalPaymentAmount'),
  sellerProductCode: text('sellerProductCode'),
  optionManageCode: text('optionManageCode'),
  customerName: text('customerName'),
  customerPhoneNumber: text('customerPhoneNumber'),
  customerId: text('customerId'),
  customerEmail: text('customerEmail'),
  receiverName: text('receiverName'),
  receiverPhoneNumber: text('receiverPhoneNumber'),
  cancelApprovalDate: timestamp('cancelApprovalDate'),
  cancelCompletedDate: timestamp('cancelCompletedDate'),
  cancelClaimRequestDate: timestamp('cancelClaimRequestDate'),
  refundStandbyStatus: text('refundStandbyStatus'),
  cancelReason: text('cancelReason'),
  returnClaimRequestDate: timestamp('returnClaimRequestDate'),
  returnClaimStatus: text('returnClaimStatus'),
  returnDetailedReason: text('returnDetailedReason'),
  returnReason: text('returnReason'),
  returnCompletedDate: timestamp('returnCompletedDate'),
  createdAt: timestamp('createdAt').notNull().defaultNow(),
  updatedAt: timestamp('updatedAt'),
})

export const esims = pgTable('esim', {
  esimId: bigint('esimId', { mode: 'number' }).primaryKey(),
  apn: text('apn'),
  tag: text('tag'),
  uid: text('uid'),
  iccid: text('iccid'),
  state: text('state'),
  autoApn: text('autoApn'),
  manualCode: text('manualCode'),
  smdpAddress: text('smdpAddress'),
  dateAssigned: timestamp('dateAssigned'),
  networkStatus: text('networkStatus'),
  serviceStatus: text('serviceStatus'),
  activationCode: text('activationCode'),
  orderProductOrderId: bigint('orderProductOrderId', { mode: 'number' }),
})

export const plans = pgTable('plan', {
  planId: serial('planId').primaryKey(),
  id: text('id'),
  isActivated: boolean('isActivated'),
  activatedAt: timestamp('activatedAt'),
  timeToBeActivatedInUTC: timestamp('timeToBeActivatedInUTC'),
  timeToBeActivatedInLocal: timestamp('timeToBeActivatedInLocal'),
  startDateEntered: text('startDateEntered'),
  startTimeEntered: integer('startTimeEntered'),
  startTimeZoneEntered: text('startTimeZoneEntered'),
  startCountryEntered: text('startCountryEntered'),
  startTime: timestamp('startTime'),
  endTime: timestamp('endTime'),
  networkStatus: text('networkStatus'),
  dataQuotaBytes: bigint('dataQuotaBytes', { mode: 'number' }),
  dataBytesRemaining: bigint('dataBytesRemaining', { mode: 'number' }),
  countriesEnabled: text('countriesEnabled'),
  esimEsimId: bigint('esimEsimId', { mode: 'number' }),
  planTypePlanTypeId: text('planTypePlanTypeId'),
  createdAt: timestamp('createdAt'),
  updatedAt: timestamp('updatedAt'),
})

export const planTypes = pgTable('plan-type', {
  planTypeId: text('planTypeId').primaryKey(),
  planCode: text('planCode'),
  dataCode: text('dataCode'),
  durationCode: text('durationCode'),
  version: text('version'),
  planNameKr: text('planNameKr'),
  planDataTypeKr: text('planDataTypeKr'),
  planDataLimitKr: text('planDataLimitKr'),
  planNameEng: text('planNameEng'),
  planDataTypeEng: text('planDataTypeEng'),
  planDataLimitEng: text('planDataLimitEng'),
  planDataDuration: integer('planDataDuration'),
  planCountriesKr: text('planCountriesKr').array(),
  planCountriesEng: text('planCountriesEng').array(),
  planCountriesIso: text('planCountriesIso').array(),
  timeZones: text('timeZones').array(),
  uid: text('uid'),
  name: text('name'),
  policyId: integer('policyId'),
  policyName: text('policyName'),
  dataQuotaMb: integer('dataQuotaMb'),
  validityDays: integer('validityDays'),
  countriesEnabled: text('countriesEnabled').array(),
})

export const naverOauth = pgTable('naver-oauth', {
  id: bigint('id', { mode: 'number' }).primaryKey(),
  accessToken: text('accessToken'),
  accessTokenUpdatedAt: timestamp('accessTokenUpdatedAt'),
})
