export { default as NSkeleton } from './NSkeleton.vue'
export type { NSkeletonProps } from './NSkeleton.vue'
export { default as NTableSkeleton } from './NTableSkeleton.vue'
export type { NTableSkeletonProps } from './NTableSkeleton.vue'
export { default as NDetailSkeleton } from './NDetailSkeleton.vue'
export type { NDetailSkeletonProps } from './NDetailSkeleton.vue'
